version: '2'
services:
  apache:
    build:
      context: .
      dockerfile: build/apache/php-7.3/Dockerfile
    ports:
      - "8080:80"
      - "9001:9000" # xdebug
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
#      VIRTUAL_HOST: "example.localhost"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  db:
    image: mariadb:10.4.13
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
      - ./backups:/var/tmp/backups
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project_name>-network

  varnish:
    build:
      context: .
      dockerfile: build/varnish/Dockerfile
    hostname: varnish
    ports:
      - "80:80"
    networks:
      - <project_name>-network
    depends_on:
      - apache
    volumes:
      - ./build/varnish/varnish6.vcl:/etc/varnish/default.vcl
      - ./build/varnish/varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=64M

  elasticsearch:
    build:
      context: .
      dockerfile: build/elasticsearch/Dockerfile
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
